myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about', views.about, name='about'),
    path(r'<int:topic_no>', views.detail, name='detail'),
    path(r'courses', views.courses, name='courses'),
    path(r'placeorder', views.place_order, name='place_order'),
    path(r'courses/<int:course_no>', views.course_detail, name="course_detail"),
    path(r'login', views.user_login, name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'myaccount', views.myaccount, name='myaccount'),
    path(r'testCookie', views.testCookie, name='testCookie'),
    path(r'password_reset', views.password_reset_request, name="password_reset"),
    path(r'register', views.user_register, name='register'),
    path(r'myorders', views.myorders, name='myorders'),
    path(r'profile_upload_page', views.profile_upload_page, name='profile_upload_page'),
    path(r'profile_upload_handler', views.profile_upload_handler, name='profile_upload_handler'),
    path(r'request_profile/<int:student_id>', views.profile_request_controller, name='request_profile'),

]

mywebappS22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="myapp/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
         name='password_reset_complete'),
]

myapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
import datetime


def validate_price(value):
    if value < 50 or value > 500:
        raise ValidationError('Price must be between 50 and 500.', params={'value': value},)


class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.name + "  " + self.category


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_price])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return self.name

    def discount(self):
        return float(self.price) * 0.9


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgary'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=50, blank=True, )
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)
    level = models.IntegerField(default=1)

    def course_list(self):
        order_list = Order.objects.filter(student=self)
        course_list = []
        for order in order_list:
            course_list.append(order.course)
        return course_list

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Order(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='orders')
    levels = models.PositiveIntegerField()
    ORDER_CHOICES = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    order_status = models.IntegerField(choices=ORDER_CHOICES, default=1)
    order_date = models.DateField()
    order_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    @classmethod
    def total_cost(self):
        return self.course.price

    def __str__(self):
        return self.course.name + " by " + self.student.username


class Profile(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    profile_name = models.CharField(max_length=100)
    update_date = models.DateField()
    profile_storage = models.FileField(upload_to="profiles/")

myapp/forms.py
from django import forms
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.forms import RadioSelect, SelectDateWidget
from django.forms import ModelForm

from myapp.models import *


class InterestForm(forms.Form):
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=[(0, 'No'), (1, 'Yes')])
    levels = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea(), label='Additional Comments', required=False)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['student', 'course', 'levels', 'order_date']
        widgets = {
            'student': RadioSelect,
            'order_date': SelectDateWidget,
        }


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='username', max_length=100)
    password = forms.CharField(required=True, label='password', max_length=20)


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Student
        fields = ['username', 'first_name', 'last_name', 'school', 'address', 'city', 'interested_in']


class ProfileUploadHandler(ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_name', 'profile_storage']

myapp/views.py
import json
import re
import time

from PIL import Image
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.urls import reverse
from django.utils import timezone
from django.conf import settings

from .forms import *
from .models import *


def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    # if 'last_login' not in request.session:
    #     return HttpResponse('Your last login was more than one hour ago')
    # last_login = request.session['last_login']
    return render(request, r'myapp/index.html', {'top_list': top_list})  # , 'last_login': last_login})


def about(request):
    count = request.session.get('about_visits', 0)
    request.session['about_visits'] = count + 1
    request.session.set_expiry(300)
    return render(request, r'myapp/about.html', {'about_visits': count})


def detail(request, topic_no):
    topic = get_object_or_404(Topic, id=topic_no)
    cour_list = Course.objects.filter(topic=topic_no)
    return render(request, r'myapp/detail.html', {'top_detail': topic, 'cou_list': cour_list})


def courses(request):
    cour_list = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'cour_list': cour_list})


@login_required(login_url='/myapp/login')
def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.student.username == request.user.username:
                if order.levels <= order.course.stages:
                    price = order.course.price
                    if price >= 150:
                        order.order_price = order.course.discount()
                    order.save()
                    msg = 'Your course has been ordered successfully.'
                else:
                    msg = 'You exceeded the number of levels for this course.'
            else:
                msg = 'You cannot order for others.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/place_order.html', {'order_form': form, 'msg': msg, 'courlist': courlist})


def course_detail(request, course_no):
    course = get_object_or_404(Course, id=course_no)
    if request.method == "POST":
        form = InterestForm(request.POST)
        if form.is_valid():
            course.interested = course.interested + 1
            course.save()
            return courses(request)
    else:
        form = InterestForm()
    return render(request, 'myapp/course_detail.html', {'form': form, 'course': course})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            json_str = json.dumps({'created_at': timezone.localtime(timezone.now())}, default=str)
            request.session['last_login'] = json_str
            request.session.set_expiry(3600)
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html', {'loginForm': LoginForm})


def user_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:login')
    else:
        form = RegisterForm
    return render(request, 'myapp/register.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url='/myapp/login')
def myaccount(request):
    usr = request.user
    if Student.objects.get(username=usr.username):
        order_list = Order.objects.filter(student=usr)
        topic_list = Topic.objects.filter(student=usr)
        course_list = list()
        course_name = [order.course.name for order in order_list]
        for name in course_name:
            if name not in course_list:
                course_list.append(name)
        return render(request, 'myapp/myaccount.html', {'firstName': usr.first_name,
                                                        'lastName': usr.last_name,
                                                        'course_list': course_list,
                                                        'topic_list': topic_list})
    else:
        msg = 'You are not a registered student.'
        return render(request, 'myapp/order_response.html', {'msg': msg})


def password_reset_request(request):
    if request.method == "POST":
        print('1')
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            print('2')
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                print('3')
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "myapp/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    print('4')
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="myapp/password_reset.html",
                  context={"password_reset_form": password_reset_form})


def testCookie(request):
    if request.method == "GET":
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            return HttpResponse("Cookie available")
        else:
            request.session.set_test_cookie()
            return HttpResponse("Please enable cookies")
    return render(request, 'myapp/index.html')


@login_required(login_url='/myapp/login')
def myorders(request):
    usr = request.user
    if Student.objects.get(username=usr.username):
        order_list = Order.objects.filter(student=usr)
        if len(order_list) != 0:
            return render(request, 'myapp/myorders.html', {'order_list': order_list})
        else:
            msg = "You haven't order any courses yet."
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        msg = 'You are not a registered student.'
        return render(request, 'myapp/order_response.html', {'msg': msg})


def profile_upload_page(request):
    return render(request, 'myapp/profile_upload.html')


def profile_upload_handler(request):
    if request.method == 'POST':
        # form = ProfileUploadHandler(request.POST, request.FILES)
        image_name = request.FILES['profile-selector'].name
        i = re.search(".png|.jpg", image_name)
        if i is not None:
            p = i.start()
            image_name = image_name[:p] + time.strftime("%a%b%d%H%M%S%Y", time.localtime()) + image_name[p:]
        else:
            return HttpResponse('Error occurred')
        profile_file = request.FILES['profile-selector']
        profile_file.name = image_name
        id = request.POST['student-id']
        student_object = Student.objects.raw("select * from myapp_student where user_ptr_id = " + id)[0]
        if student_object:
            savor = Profile(profile_name=image_name, profile_storage=profile_file,
                            update_date=timezone.localtime(timezone.now()), student=student_object)
            savor.save()
            return HttpResponseRedirect(reverse('myapp:index'))
        else:
            return HttpResponse('Not a validate student!')


def profile_request_controller(request, student_id):
    id_list = [student_id]
    student = Student.objects.raw("select * from myapp_student where user_ptr_id = %s", id_list)[0]
    target_object = Profile.objects.filter(student_id=student)
    if len(target_object) > 0:
        storage_path = settings.MEDIA_ROOT + target_object[0].profile_storage.__str__()
    else:
        return HttpResponse("Error occurred")
    try:
        with open(storage_path, "rb") as f:
            return HttpResponse(f.read(), content_type="image/jpeg")
    except IOError:
        red = Image.new('RGBA', (1, 1), (255, 0, 0, 0))
        response = HttpResponse(content_type="image/jpeg")
        red.save(response, "JPEG")

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h3>This is an E-learning Website! Search our Topics to find all available Courses.</h3>
    <h3> {{ about_visits }} visited in total</h3>
    {#    <p><a href="index0.html"></a></p>#}
    {#    <p><a href={% url "myapp:index" %}></a></p>#}
{% endblock %}

{% block myhdg %}Hello {{ user.getUserName }}{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About page</title>
</head>
<body>
    <h3>This is an E-learning Website! Search our Topics to find all available Courses.</h3>
{#    <p><a href="index0.html"></a></p>#}
    <p><a href={% url "myapp:index" %}></a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    <script type="text/javascript"> (function () {
        var css = document.createElement('link');
        css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css';
        css.rel = 'stylesheet';
        css.type = 'text/css';
        document.getElementsByTagName('head')[0].appendChild(css);
    })(); </script>


    <link rel="stylesheet" href="{% static 'myapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" crossorigin="anonymous"
          media="all" type="text/css">
    <link rel="stylesheet" href="{% static 'myapp/css/fileinput.min.css' %}" media="all" type="text/css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'myapp/js/plugins/buffer.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'myapp/js/plugins/filetype.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'myapp/js/plugins/piexif.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'myapp/js/plugins/sortable.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'myapp/js/bootstrap.bundle.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'myapp/js/fileinput.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/themes/fa5/theme.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand font-weight-bolder mr-3" href="{% url 'myapp:index' %}"><img
            src="{% static 'myapp/img/logo.png' %}"></a>
    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault"
            aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsDefault">
        <ul class="navbar-nav mr-auto align-items-center">
            <form class="bd-search hidden-sm-down">
                <input type="text" class="form-control bg-graylight border-0 font-weight-bold" id="search-input"
                       placeholder="Search..." autocomplete="off">
                <div class="dropdown-menu bd-search-results" id="search-results">
                </div>
            </form>
        </ul>
        <ul class="navbar-nav ml-auto align-items-center">
            {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'myapp:index' %}">Hello {{ request.user.username }}</a>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:profile_upload_page' %}"><img class="rounded-circle mr-2"
                                                                                     src="{% url 'myapp:request_profile' request.user.id %}"
                                                                                     width="30">
                        <span class="align-middle">{{ request.user.username }}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:logout' %}"><span class="align-middle">Log out</span></a>
                </li>

            {% else %}
                <a class="nav-link active" href="{% url 'myapp:index' %}">Hello User!</a>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:login' %}"><img class="rounded-circle mr-2"
                                                                            src="{% static 'myapp/img/av.png' %}"
                                                                            width="30"><span
                            class="align-middle">Log in</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:register' %}"><span class="align-middle">Registration</span></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main">
    <div class="container mb-4">
        {% block body_block %}*** {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            {% if request.user.is_authenticated %}
                <li class="hbar1"><a href="{% url 'myapp:myorders' %}">Check All Your Orders</a><br></li>
            {% endif %}
            <li class="hbar1"><a href="{% url 'myapp:about' %}">Find out about our E-Learning site</a><br></li>
            <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
            <li class="hbar1"><a href="{% url 'myapp:courses' %}">Click here to check available courses</a><br/></li>
        </ul>
    </div>
</main>
</body>

myapp/templates/myapp/course_detail.html
{% extends 'Myapp/base.html' %}

{% block body_block %}
    <p>{{ course.name }}   ${{ course.price }} , its interested No is {{ course.interested }}</p>
    {% if course.for_everyone %}
        <p>This course is for everyone</p>
    {% else %}
        <p>This course is not for everyone</p>
    {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input type = "submit" value="submnit" />
        </form>
{% endblock %}

{% block myhdg %}{% endblock %}
{% block title %}Course_detail{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <div class="row justify-content-center">
        <div class="col-3">
            <h3>Available Courses:</h3>
        </div>
    </div>
    <table>
        {% for course in cour_list %}
            <ul class="list-group list-group-horizontal">
                <li class="list-group-item" style="width: 7%">{{ course.id }}</li>
                <li class="list-group-item flex-fill"><a href= {% url "myapp:course_detail" course.id %}>{{ course.name }}</a></li>
                <li class="list-group-item">{{ course.price }}</li>
            </ul>
        {% endfor %}
    </table>
    <ul>
        <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
        <li class="hbar1"><a href="{% url 'myapp:place_order' %}">Click here to place an order</a><br></li>
    </ul>
{% endblock %}

{% block myhdg %}Hello {{ user.getUserName }}{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">{{ top_detail.category }}</li>
            <li class="breadcrumb-item active">{{ top_detail.name }}</li>
        </ol>
    </nav>
    {% for course in cou_list %}
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item flex-fill"><a href="{% url 'myapp:course_detail' course.id %}">{{ course.name }}</a></li>
            <li class="list-group-item">{{ course.price }}</li>
        </ul>
    {% endfor %}
    <p><a href={% url "myapp:index" %}></a></p>
{% endblock %}

{% block myhdg %}Hello {{ user.getUserName }}{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic Detail Page</title>
</head>
<body>
    <h3>Topic: {{ top_detail.name }}</h3>
    <h3>Category: {{ top_detail.category }}</h3>
    <h3>Courses under this category:</h3>
    <table>
        {% for course in cou_list %}
        <tr>
            <td>{{ course.name }}</td>
            <td>{{ course.price }}</td>
        </tr>
        {% endfor %}
    </table>
    <p><a href={% url "myapp:index" %}></a></p>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if top_list %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-3">
                    <h2>List of Topics</h2>
                </div>
            </div>
            <div class="container-lg">
                <div class="row">
                {% load static %}
                    {% for top in top_list %}
                        <div class="card mb-3" style="width: 30%;margin: 1.6%">
                            <img src="{% static 'myapp/img/course.jpg' %}">
                            <div class="card-body">
                                <h4 class="card-title">{{ top.name }}</h4>
                                <a class="btn btn-primary" href="{% url 'myapp:detail' top.id %}">Check courses</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'Myapp/base.html' %}
<!--user.get_username可以从request中获取user name-->
{% block body_block %}
    {%  block content %}
        <div>
             {%  if course_list %}
                <h2> Ordered Courses</h2>
                <ol>
                   {%  for crs in course_list %}
                       <li>{{ crs }}</li>
                   {% endfor %}
                 </ol>
            {%  else %}
                <Strong> There is no Course </Strong>
            {% endif %}
        </div>

        <div>
            {%  if topic_list %}
                <h2> Topics' of Order Courses </h2>
                <ol>
                   {%  for tp in topic_list %}
                       <li>{{ tp.name }}</li>
                   {% endfor %}
                 </ol>
            {%  else %}
                <Strong> There is no interested topic </Strong>
            {% endif %}
        </div>

    {%  endblock %}
{% endblock %}
{% block myhdg %}Hello {{ firstName }} {{ lastName }}{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h3>{{ msg }}</h3>
{#    <p><a href="index0.html"></a></p>#}
{#    <p><a href={% url "myapp:index" %}></a></p>#}
{% endblock %}

{% block myhdg %}Hello {{ user.getUserName }}{% endblock %}

myapp/templates/myapp/password_reset.html
{% extends 'Myapp/base.html' %}

{% block body_block %}

	{% load crispy_forms_tags %}

	<!--Reset Password-->
	<div>
  	 	<h2>Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}
            <button type="submit">Send email</button>
        </form>
  	</div>

{% endblock %}

myapp/templates/myapp/password_reset_complete.html
{% extends "Myapp/base.html" %}

{% block body_block %}
  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'myapp:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h3>Available Courses:</h3>
    <table>
        {% for course in courlist %}
        <tr>
            <td>{{ course.id }}</td>
            <td>{{ course.name }}</td>
            <td>{{ course.price }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>Place Order Here: </h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ order_form }}
        <input type="submit" value="Submit">
    </form>
    <p><a href={% url "myapp:index" %}></a></p>
{% endblock %}

{% block myhdg %}Hello {{ user.getUserName }}{% endblock %}

myapp/templates/myapp/register.html
{%  extends 'Myapp/base.html' %}
{% block body_block %}
        <div>
            <form method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register"/>
            </form>
        </div>
{% endblock  %}
{% block myhdg %}Welcome, please Register{% endblock %}
{% block title %}Register_Page{% endblock %}